apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  labels:
    app.kubernetes.io/name: grafanacontactpoint
    app.kubernetes.io/instance: grafanacontactpoint-sample
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: grafana-operator
  name: grafanacontactpoint-sample
spec:
  name: grafanacontactpoint-sample
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  receivers:
  - type: email
    settings:
      addresses: email1@email.com
  - type: email
    settings:
      addresses: email2@email.com
