apiVersion: v1
kind: Secret
metadata:
  name: contact-mails
stringData:
  alert-mails: "foo@example.com"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: grafanacontactpoint-sample
spec:
  name: grafanacontactpoint-sample
  type: "email"
  instanceSelector:
    matchLabels:
      instance: my-grafana-stack
  settings:
    subject: 'Grafana Alert'
  valuesFrom:
    - targetPath: addresses
      valueFrom:
        secretKeyRef:
          name: contact-mails
          key: alert-mails
