apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 400m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - name: dashboards-dir
            mountPath: /tmp/dashboards
      volumes:
        - name: dashboards-dir
          emptyDir: {}
