resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      kind: Deployment
      version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/grafana/grafana-operator
    newName: ko.local/grafana/grafana-operator
    newTag: latest
