documentation:
- changed-files:
  - any-glob-to-any-file: docs/**
  - any-glob-to-any-file: examples/**

feature:
 - head-branch: ['^feature', 'feature', '^feat']

bugfix:
 - head-branch: ['^fix', 'fix', '^bugfix']

chore:
 - head-branch: ['^chore', '^ci', ^refactor]

test:
 - head-branch: ['^test']
