run:
  timeout: 4m

linters:
  disable-all: false
  enable:
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - gosec
    - gosimple
    - govet
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - thelper
    - unparam
    - unused
    - whitespace

linters-settings:
  dogsled:
    max-blank-identifiers: 2

  errcheck:
    check-type-assertions: true
    check-blank: true

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  goconst:
    min-len: 3
    min-occurrences: 3

  gocyclo:
    min-complexity: 25

  gosimple:
    checks: ["all"]

  makezero:
    always: false

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 30

  nolintlint:
    allow-unused: false
    allow-no-explanation: []
    require-explanation: false
    require-specific: false

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  revive:
    ignore-generated-header: true
    severity: warning

  staticcheck:
    checks: ["all"]

  thelper:
    test:
      first: true
      name: true
      begin: true
    benchmark:
      first: true
      name: true
      begin: true
    tb:
      first: true
      name: true
      begin: true

  unparam:
    check-exported: true

  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude:
    - "G305: File traversal when extracting zip/tar archive" # Related to json_fetch.go: target = filepath.Join(extractPath, header.Name)
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
        - unparam
        - unused
