version: "2"
linters:
  enable:
    - dogsled
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - prealloc
    - revive
    - thelper
    - unparam
    - usestdlibvars
    - whitespace

  settings:
    dogsled:
      max-blank-identifiers: 2

    errcheck:
      check-type-assertions: true
      check-blank: true

    errorlint:
      errorf: true
      asserts: true
      comparison: true

    exhaustive:
      default-signifies-exhaustive: false

    goconst:
      min-len: 3
      min-occurrences: 3

    gocyclo:
      min-complexity: 25

    makezero:
      always: false

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    nestif:
      min-complexity: 30

    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: false
      require-specific: false

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    revive:
      severity: warning

    staticcheck:
      checks:
        - all

    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true

    unparam:
      check-exported: true

    whitespace:
      multi-if: false
      multi-func: false

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - unparam
          - unused
        path: _test\.go

formatters:
  enable:
    - gofumpt
