module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.24.2

replace github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d

require github.com/operator-framework/operator-registry v1.23.2 // cmd/opm
