// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Grafana Operator API",
    "version": "1.0.0"
  },
  "paths": {
    "/api": {
      "get": {
        "security": [],
        "summary": "List available api versions",
        "operationId": "ListAPIVersions",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiVersions"
            }
          }
        }
      }
    },
    "/api/v1/grafana": {
      "post": {
        "summary": "Create a Grafana instance",
        "operationId": "CreateGrafana",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Grafana"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Grafana"
            }
          },
          "default": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    },
    "/api/v1/grafana/{namespace}": {
      "get": {
        "summary": "List available Grafanas by Namespace",
        "operationId": "ListGrafanas",
        "parameters": [
          {
            "type": "string",
            "description": "Name of namespace",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Grafana"
              }
            }
          },
          "default": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    },
    "/info": {
      "get": {
        "security": [],
        "summary": "Get info about Grafana as a Service",
        "operationId": "Info",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Info"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiVersions": {
      "required": [
        "versions"
      ],
      "properties": {
        "versions": {
          "description": "versions are the api versions that are available.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Grafana": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": false
        },
        "spec": {
          "$ref": "#/definitions/GrafanaSpec"
        },
        "status": {
          "$ref": "#/definitions/GrafanaStatus"
        }
      }
    },
    "GrafanaPlugin": {
      "type": "object",
      "properties": {
        "name": {
          "type": "integer"
        },
        "version": {
          "type": "string"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "GrafanaSpec": {
      "type": "object",
      "properties": {
        "AdminPassword": {
          "type": "string"
        },
        "AdminUser": {
          "type": "string"
        },
        "Anonymous": {
          "type": "boolean"
        },
        "BasicAuth": {
          "type": "boolean"
        },
        "DisableLoginForm": {
          "type": "boolean"
        },
        "DisableSignoutMenu": {
          "type": "boolean"
        },
        "Hostname": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": true
        },
        "LogLevel": {
          "type": "string"
        },
        "Secrets": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-nullable": false,
          "x-omitempty": true
        }
      },
      "x-nullable": false
    },
    "GrafanaStatus": {
      "type": "object",
      "properties": {
        "failedPlugins": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GrafanaPlugin"
          }
        },
        "installedPlugins": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GrafanaPlugin"
          }
        },
        "phase": {
          "type": "integer"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "Info": {
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "account": {
          "description": "account id",
          "type": "string"
        },
        "account_name": {
          "description": "account name",
          "type": "string"
        },
        "authUrl": {
          "description": "Identity Endpoint",
          "type": "string"
        },
        "domain": {
          "description": "user's domain name",
          "type": "string"
        },
        "id": {
          "description": "userid",
          "type": "string"
        },
        "name": {
          "description": "username",
          "type": "string"
        },
        "roles": {
          "description": "list of roles the user has in the given scope",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "error": {
      "description": "the error model is a model for all the error responses coming from Grafana as a service\n",
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "The error code",
          "type": "integer",
          "x-nullable": false
        },
        "message": {
          "description": "The error message",
          "type": "string",
          "x-nullable": false
        }
      }
    }
  },
  "responses": {
    "errorResponse": {
      "description": "Error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  },
  "securityDefinitions": {
    "keystone": {
      "description": "OpenStack Keystone Authentication",
      "type": "apiKey",
      "name": "x-auth-token",
      "in": "header"
    }
  },
  "security": [
    {
      "keystone": null
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Grafana Operator API",
    "version": "1.0.0"
  },
  "paths": {
    "/api": {
      "get": {
        "security": [],
        "summary": "List available api versions",
        "operationId": "ListAPIVersions",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiVersions"
            }
          }
        }
      }
    },
    "/api/v1/grafana": {
      "post": {
        "summary": "Create a Grafana instance",
        "operationId": "CreateGrafana",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Grafana"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Grafana"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/grafana/{namespace}": {
      "get": {
        "summary": "List available Grafanas by Namespace",
        "operationId": "ListGrafanas",
        "parameters": [
          {
            "type": "string",
            "description": "Name of namespace",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Grafana"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/info": {
      "get": {
        "security": [],
        "summary": "Get info about Grafana as a Service",
        "operationId": "Info",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Info"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiVersions": {
      "required": [
        "versions"
      ],
      "properties": {
        "versions": {
          "description": "versions are the api versions that are available.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Grafana": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": false
        },
        "spec": {
          "$ref": "#/definitions/GrafanaSpec"
        },
        "status": {
          "$ref": "#/definitions/GrafanaStatus"
        }
      }
    },
    "GrafanaPlugin": {
      "type": "object",
      "properties": {
        "name": {
          "type": "integer"
        },
        "version": {
          "type": "string"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "GrafanaSpec": {
      "type": "object",
      "properties": {
        "AdminPassword": {
          "type": "string"
        },
        "AdminUser": {
          "type": "string"
        },
        "Anonymous": {
          "type": "boolean"
        },
        "BasicAuth": {
          "type": "boolean"
        },
        "DisableLoginForm": {
          "type": "boolean"
        },
        "DisableSignoutMenu": {
          "type": "boolean"
        },
        "Hostname": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": true
        },
        "LogLevel": {
          "type": "string"
        },
        "Secrets": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-nullable": false,
          "x-omitempty": true
        }
      },
      "x-nullable": false
    },
    "GrafanaStatus": {
      "type": "object",
      "properties": {
        "failedPlugins": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GrafanaPlugin"
          }
        },
        "installedPlugins": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GrafanaPlugin"
          }
        },
        "phase": {
          "type": "integer"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "Info": {
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "account": {
          "description": "account id",
          "type": "string"
        },
        "account_name": {
          "description": "account name",
          "type": "string"
        },
        "authUrl": {
          "description": "Identity Endpoint",
          "type": "string"
        },
        "domain": {
          "description": "user's domain name",
          "type": "string"
        },
        "id": {
          "description": "userid",
          "type": "string"
        },
        "name": {
          "description": "username",
          "type": "string"
        },
        "roles": {
          "description": "list of roles the user has in the given scope",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "error": {
      "description": "the error model is a model for all the error responses coming from Grafana as a service\n",
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "The error code",
          "type": "integer",
          "x-nullable": false
        },
        "message": {
          "description": "The error message",
          "type": "string",
          "x-nullable": false
        }
      }
    }
  },
  "responses": {
    "errorResponse": {
      "description": "Error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  },
  "securityDefinitions": {
    "keystone": {
      "description": "OpenStack Keystone Authentication",
      "type": "apiKey",
      "name": "x-auth-token",
      "in": "header"
    }
  },
  "security": [
    {
      "keystone": []
    }
  ]
}`))
}
