// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Grafana Operator API",
    "version": "1.0.0"
  },
  "paths": {
    "/api": {
      "get": {
        "security": [],
        "summary": "List available api versions",
        "operationId": "ListAPIVersions",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiVersions"
            }
          }
        }
      }
    },
    "/api/v1/grafana": {
      "post": {
        "summary": "Create a Grafana instance",
        "operationId": "CreateGrafana",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Grafana"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "description"
              ],
              "properties": {
                "hostname": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          },
          "default": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    },
    "/api/v1/grafana/{namespace}": {
      "get": {
        "summary": "List available Grafanas by Namespace",
        "operationId": "ListGrafanas",
        "parameters": [
          {
            "type": "string",
            "description": "Name of namespace",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Grafana"
              }
            }
          },
          "default": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    },
    "/api/v1/grafanaproxy": {
      "post": {
        "summary": "Create a Grafana Proxy instance",
        "operationId": "CreateGrafanaProxy",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GrafanaProxy"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "description"
              ],
              "properties": {
                "hostname": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          },
          "default": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    },
    "/info": {
      "get": {
        "security": [],
        "summary": "Get info about Grafana as a Service",
        "operationId": "Info",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Info"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiVersions": {
      "required": [
        "versions"
      ],
      "properties": {
        "versions": {
          "description": "versions are the api versions that are available.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Grafana": {
      "type": "object",
      "properties": {
        "config": {
          "$ref": "#/definitions/GrafanaConfig"
        },
        "name": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        },
        "namespace": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        }
      }
    },
    "GrafanaConfig": {
      "type": "object",
      "properties": {
        "adminPassword": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"adminPassword\""
        },
        "adminUser": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"adminUser\""
        },
        "anonymous": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"anonymous\""
        },
        "authProxy": {
          "type": "object",
          "properties": {
            "clientSecret": {
              "type": "string",
              "x-go-custom-tag": "yaml:\"clientSecret\"",
              "x-nullable": true
            },
            "enabled": {
              "type": "boolean",
              "x-go-custom-tag": "yaml:\"enabled\""
            }
          },
          "x-go-custom-tag": "yaml:\"authProxy\""
        },
        "autoAssignOrg": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"autoAssignOrg\""
        },
        "autoAssignOrgRole": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"autoAssignOrgRole\""
        },
        "basicAuth": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"basicAuth\""
        },
        "disableLoginForm": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"disableLoginForm\""
        },
        "disableSignoutMenu": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"disableSignoutMenu\""
        },
        "grafanaGroupRoleMap": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"grafanaGroupRoleMap\""
        },
        "ingressHost": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"hostname\"",
          "x-nullable": false
        },
        "logLevel": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"logLevel\""
        },
        "orgName": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"orgName\""
        }
      },
      "x-nullable": false
    },
    "GrafanaPlugin": {
      "type": "object",
      "properties": {
        "name": {
          "type": "integer"
        },
        "version": {
          "type": "string"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "GrafanaProxy": {
      "type": "object",
      "properties": {
        "config": {
          "$ref": "#/definitions/GrafanaProxyConfig"
        },
        "name": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        },
        "namespace": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        }
      }
    },
    "GrafanaProxyConfig": {
      "type": "object",
      "properties": {
        "clientSecret": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"clientSecret\"",
          "x-nullable": true
        },
        "connectors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "ingressHost": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"ingressHost\"",
          "x-nullable": false
        }
      },
      "x-nullable": false
    },
    "GrafanaStatus": {
      "type": "object",
      "properties": {
        "installedPlugins": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GrafanaPlugin"
          }
        },
        "phase": {
          "type": "integer"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "Info": {
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "account": {
          "description": "account id",
          "type": "string"
        },
        "account_name": {
          "description": "account name",
          "type": "string"
        },
        "authUrl": {
          "description": "Identity Endpoint",
          "type": "string"
        },
        "domain": {
          "description": "user's domain name",
          "type": "string"
        },
        "id": {
          "description": "userid",
          "type": "string"
        },
        "name": {
          "description": "username",
          "type": "string"
        },
        "roles": {
          "description": "list of roles the user has in the given scope",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "error": {
      "description": "the error model is a model for all the error responses coming from Grafana as a service\n",
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "The error code",
          "type": "integer",
          "x-nullable": false
        },
        "message": {
          "description": "The error message",
          "type": "string",
          "x-nullable": false
        }
      }
    }
  },
  "responses": {
    "errorResponse": {
      "description": "Error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  },
  "securityDefinitions": {
    "keystone": {
      "description": "OpenStack Keystone Authentication",
      "type": "apiKey",
      "name": "x-auth-token",
      "in": "header"
    }
  },
  "security": [
    {
      "keystone": null
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Grafana Operator API",
    "version": "1.0.0"
  },
  "paths": {
    "/api": {
      "get": {
        "security": [],
        "summary": "List available api versions",
        "operationId": "ListAPIVersions",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiVersions"
            }
          }
        }
      }
    },
    "/api/v1/grafana": {
      "post": {
        "summary": "Create a Grafana instance",
        "operationId": "CreateGrafana",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Grafana"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/createGrafanaCreatedBody"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/grafana/{namespace}": {
      "get": {
        "summary": "List available Grafanas by Namespace",
        "operationId": "ListGrafanas",
        "parameters": [
          {
            "type": "string",
            "description": "Name of namespace",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Grafana"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/api/v1/grafanaproxy": {
      "post": {
        "summary": "Create a Grafana Proxy instance",
        "operationId": "CreateGrafanaProxy",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GrafanaProxy"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/createGrafanaProxyCreatedBody"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/info": {
      "get": {
        "security": [],
        "summary": "Get info about Grafana as a Service",
        "operationId": "Info",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Info"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiVersions": {
      "required": [
        "versions"
      ],
      "properties": {
        "versions": {
          "description": "versions are the api versions that are available.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Grafana": {
      "type": "object",
      "properties": {
        "config": {
          "$ref": "#/definitions/GrafanaConfig"
        },
        "name": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        },
        "namespace": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        }
      }
    },
    "GrafanaConfig": {
      "type": "object",
      "properties": {
        "adminPassword": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"adminPassword\""
        },
        "adminUser": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"adminUser\""
        },
        "anonymous": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"anonymous\""
        },
        "authProxy": {
          "$ref": "#/definitions/grafanaConfigAuthProxy"
        },
        "autoAssignOrg": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"autoAssignOrg\""
        },
        "autoAssignOrgRole": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"autoAssignOrgRole\""
        },
        "basicAuth": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"basicAuth\""
        },
        "disableLoginForm": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"disableLoginForm\""
        },
        "disableSignoutMenu": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"disableSignoutMenu\""
        },
        "grafanaGroupRoleMap": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"grafanaGroupRoleMap\""
        },
        "ingressHost": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"hostname\"",
          "x-nullable": false
        },
        "logLevel": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"logLevel\""
        },
        "orgName": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"orgName\""
        }
      },
      "x-nullable": false
    },
    "GrafanaPlugin": {
      "type": "object",
      "properties": {
        "name": {
          "type": "integer"
        },
        "version": {
          "type": "string"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "GrafanaProxy": {
      "type": "object",
      "properties": {
        "config": {
          "$ref": "#/definitions/GrafanaProxyConfig"
        },
        "name": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        },
        "namespace": {
          "description": "name of Grafana instance",
          "type": "string",
          "maxLength": 20,
          "pattern": "^[a-z]([-a-z0-9]*[a-z0-9])?$",
          "x-nullable": true
        }
      }
    },
    "GrafanaProxyConfig": {
      "type": "object",
      "properties": {
        "clientSecret": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"clientSecret\"",
          "x-nullable": true
        },
        "connectors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "ingressHost": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"ingressHost\"",
          "x-nullable": false
        }
      },
      "x-nullable": false
    },
    "GrafanaStatus": {
      "type": "object",
      "properties": {
        "installedPlugins": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GrafanaPlugin"
          }
        },
        "phase": {
          "type": "integer"
        }
      },
      "x-nullable": false,
      "readOnly": true
    },
    "Info": {
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "account": {
          "description": "account id",
          "type": "string"
        },
        "account_name": {
          "description": "account name",
          "type": "string"
        },
        "authUrl": {
          "description": "Identity Endpoint",
          "type": "string"
        },
        "domain": {
          "description": "user's domain name",
          "type": "string"
        },
        "id": {
          "description": "userid",
          "type": "string"
        },
        "name": {
          "description": "username",
          "type": "string"
        },
        "roles": {
          "description": "list of roles the user has in the given scope",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "createGrafanaCreatedBody": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "hostname": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "x-go-gen-location": "operations"
    },
    "createGrafanaProxyCreatedBody": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "hostname": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "x-go-gen-location": "operations"
    },
    "error": {
      "description": "the error model is a model for all the error responses coming from Grafana as a service\n",
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "The error code",
          "type": "integer",
          "x-nullable": false
        },
        "message": {
          "description": "The error message",
          "type": "string",
          "x-nullable": false
        }
      }
    },
    "grafanaConfigAuthProxy": {
      "type": "object",
      "properties": {
        "clientSecret": {
          "type": "string",
          "x-go-custom-tag": "yaml:\"clientSecret\"",
          "x-nullable": true
        },
        "enabled": {
          "type": "boolean",
          "x-go-custom-tag": "yaml:\"enabled\""
        }
      },
      "x-go-custom-tag": "yaml:\"authProxy\"",
      "x-go-gen-location": "models"
    }
  },
  "responses": {
    "errorResponse": {
      "description": "Error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  },
  "securityDefinitions": {
    "keystone": {
      "description": "OpenStack Keystone Authentication",
      "type": "apiKey",
      "name": "x-auth-token",
      "in": "header"
    }
  },
  "security": [
    {
      "keystone": []
    }
  ]
}`))
}
