apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - example.com
  secretName: core-cert
  revisionHistoryLimit: 1
