# permissions for end users to edit grafanalibrarypanels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanalibrarypanel-editor-role
rules:
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanalibrarypanels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanalibrarypanels/status
  verbs:
  - get
