// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/integr8ly/grafana-operator/v3/pkg/api/models"
)

// CreateGrafanaCreatedCode is the HTTP code returned for type CreateGrafanaCreated
const CreateGrafanaCreatedCode int = 201

/*CreateGrafanaCreated OK

swagger:response createGrafanaCreated
*/
type CreateGrafanaCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Grafana `json:"body,omitempty"`
}

// NewCreateGrafanaCreated creates CreateGrafanaCreated with default headers values
func NewCreateGrafanaCreated() *CreateGrafanaCreated {

	return &CreateGrafanaCreated{}
}

// WithPayload adds the payload to the create grafana created response
func (o *CreateGrafanaCreated) WithPayload(payload *models.Grafana) *CreateGrafanaCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create grafana created response
func (o *CreateGrafanaCreated) SetPayload(payload *models.Grafana) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGrafanaCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateGrafanaDefault Error

swagger:response createGrafanaDefault
*/
type CreateGrafanaDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateGrafanaDefault creates CreateGrafanaDefault with default headers values
func NewCreateGrafanaDefault(code int) *CreateGrafanaDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateGrafanaDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create grafana default response
func (o *CreateGrafanaDefault) WithStatusCode(code int) *CreateGrafanaDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create grafana default response
func (o *CreateGrafanaDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create grafana default response
func (o *CreateGrafanaDefault) WithPayload(payload *models.Error) *CreateGrafanaDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create grafana default response
func (o *CreateGrafanaDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGrafanaDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
