// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateGrafanaHandlerFunc turns a function with the right signature into a create grafana handler
type CreateGrafanaHandlerFunc func(CreateGrafanaParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateGrafanaHandlerFunc) Handle(params CreateGrafanaParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateGrafanaHandler interface for that can handle valid create grafana params
type CreateGrafanaHandler interface {
	Handle(CreateGrafanaParams, interface{}) middleware.Responder
}

// NewCreateGrafana creates a new http.Handler for the create grafana operation
func NewCreateGrafana(ctx *middleware.Context, handler CreateGrafanaHandler) *CreateGrafana {
	return &CreateGrafana{Context: ctx, Handler: handler}
}

/*CreateGrafana swagger:route POST /api/v1/grafana createGrafana

Create a Grafana instance

*/
type CreateGrafana struct {
	Context *middleware.Context
	Handler CreateGrafanaHandler
}

func (o *CreateGrafana) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateGrafanaParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
