// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListAPIVersionsHandlerFunc turns a function with the right signature into a list API versions handler
type ListAPIVersionsHandlerFunc func(ListAPIVersionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAPIVersionsHandlerFunc) Handle(params ListAPIVersionsParams) middleware.Responder {
	return fn(params)
}

// ListAPIVersionsHandler interface for that can handle valid list API versions params
type ListAPIVersionsHandler interface {
	Handle(ListAPIVersionsParams) middleware.Responder
}

// NewListAPIVersions creates a new http.Handler for the list API versions operation
func NewListAPIVersions(ctx *middleware.Context, handler ListAPIVersionsHandler) *ListAPIVersions {
	return &ListAPIVersions{Context: ctx, Handler: handler}
}

/*ListAPIVersions swagger:route GET /api listApiVersions

List available api versions

*/
type ListAPIVersions struct {
	Context *middleware.Context
	Handler ListAPIVersionsHandler
}

func (o *ListAPIVersions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAPIVersionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
