namespace: grafana

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: grafana-operator-controller-manager
    patch: |
      - op: "add"
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  - target:
      kind: ClusterRole
    patch: |
      - op: replace
        path: /kind
        value: Role
  - target:
      kind: ClusterRoleBinding
    patch: |
      - op: replace
        path: /kind
        value: RoleBinding
      - op: replace
        path: /roleRef/kind
        value: Role
