extraObjects:
  - |
    apiVersion: grafana.integreatly.org/v1beta1
    kind: Grafana
    metadata:
      name: {{ include "grafana.fullname" . }}
      namespace: {{ include "grafana.namespace" . }}
      labels:
        {{- include "grafana.labels" . | nindent 4 }}
    spec:
      external:
        url: "http://{{ include "grafana.fullname" . }}.{{ include "grafana.namespace" . }}.svc.cluster.local:{{ .Values.service.port }}/"
        adminUser:
          name: {{ (tpl .Values.admin.existingSecret .) | default (include "grafana.fullname" .) }}
          key: {{ .Values.admin.userKey | default "admin-user" }}
        adminPassword:
          name: {{ (tpl .Values.admin.existingSecret .) | default (include "grafana.fullname" .) }}
          key: {{ .Values.admin.passwordKey | default "admin-password" }}
