---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: old-format
spec:
  name: required
  instanceSelector:
    matchLabels:
      instance: my-grafana-stack
  type: "email"
  settings:
    subject: 'Grafana Alert'
  valuesFrom:
    - targetPath: addresses
      valueFrom:
        secretKeyRef:
          name: contacts
          key: alert-mails
