apiVersion: v1
kind: Secret
metadata:
  name: contacts
stringData:
  alert-mails: "foo@example.com"
  alert-hook: "webhook.example.invalid"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: grafanacontactpoint-sample
spec:
  name: Optional Name
  instanceSelector:
    matchLabels:
      instance: my-grafana-stack
  # Editing ContactPoints in the UI is disabled by default
  editable: true # editable is immutable and can only be set at creation
  receivers:
    - type: email
      settings:
        subject: Grafana Alert
      valuesFrom:
        - targetPath: addresses
          valueFrom:
            secretKeyRef:
              name: contacts
              key: alert-mails
    - type: webhook
      settings:
        title: Grafana Alert
      valuesFrom:
        - targetPath: url
          valueFrom:
            secretKeyRef:
              name: contacts
              key: alert-hook
