package v1alpha1

//
//// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaSpec.
//func (in *GrafanaSpec) DeepCopy() *GrafanaSpec {
//	if in == nil {
//		return nil
//	}
//	out := new(GrafanaSpec)
//	in.DeepCopyInto(out)
//	return out
//}
