// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GrafanaConfig grafana config
// swagger:model GrafanaConfig
type GrafanaConfig struct {

	// admin password
	AdminPassword string `json:"adminPassword,omitempty" yaml:"adminPassword"`

	// admin user
	AdminUser string `json:"adminUser,omitempty" yaml:"adminUser"`

	// anonymous
	Anonymous bool `json:"anonymous,omitempty" yaml:"anonymous"`

	// auto assign org
	AutoAssignOrg bool `json:"autoAssignOrg,omitempty" yaml:"autoAssignOrg"`

	// auto assign org role
	AutoAssignOrgRole string `json:"autoAssignOrgRole,omitempty" yaml:"autoAssignOrgRole"`

	// basic auth
	BasicAuth bool `json:"basicAuth,omitempty" yaml:"basicAuth"`

	// disable login form
	DisableLoginForm bool `json:"disableLoginForm,omitempty" yaml:"disableLoginForm"`

	// disable signout menu
	DisableSignoutMenu bool `json:"disableSignoutMenu,omitempty" yaml:"disableSignoutMenu"`

	// grafana group role map
	GrafanaGroupRoleMap string `json:"grafanaGroupRoleMap,omitempty" yaml:"grafanaGroupRoleMap"`

	// hostname
	Hostname string `json:"hostname,omitempty" yaml:"hostname"`

	// log level
	LogLevel string `json:"logLevel,omitempty" yaml:"logLevel"`
}

// Validate validates this grafana config
func (m *GrafanaConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrafanaConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrafanaConfig) UnmarshalBinary(b []byte) error {
	var res GrafanaConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
