// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GrafanaProxyConfig grafana proxy config
// swagger:model GrafanaProxyConfig
type GrafanaProxyConfig struct {

	// client secret
	ClientSecret *string `json:"clientSecret,omitempty" yaml:"clientSecret"`

	// connectors
	Connectors []string `json:"connectors"`

	// ingress host
	IngressHost string `json:"ingressHost,omitempty" yaml:"ingressHost"`
}

// Validate validates this grafana proxy config
func (m *GrafanaProxyConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrafanaProxyConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrafanaProxyConfig) UnmarshalBinary(b []byte) error {
	var res GrafanaProxyConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
