// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GrafanaConfigAuthProxy grafana config auth proxy
// swagger:model grafanaConfigAuthProxy
type GrafanaConfigAuthProxy struct {

	// client secret
	ClientSecret *string `json:"clientSecret,omitempty" yaml:"clientSecret"`

	// enabled
	Enabled bool `json:"enabled,omitempty" yaml:"enabled"`
}

// Validate validates this grafana config auth proxy
func (m *GrafanaConfigAuthProxy) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrafanaConfigAuthProxy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrafanaConfigAuthProxy) UnmarshalBinary(b []byte) error {
	var res GrafanaConfigAuthProxy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
