// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GrafanaAuthProxy grafana auth proxy
// swagger:model GrafanaAuthProxy
type GrafanaAuthProxy struct {

	// client secret
	ClientSecret string `json:"clientSecret,omitempty"`

	// connectors
	Connectors []string `json:"connectors"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this grafana auth proxy
func (m *GrafanaAuthProxy) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrafanaAuthProxy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrafanaAuthProxy) UnmarshalBinary(b []byte) error {
	var res GrafanaAuthProxy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
