// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GrafanaStatus grafana status
// swagger:model GrafanaStatus
type GrafanaStatus struct {

	// installed plugins
	InstalledPlugins []GrafanaPlugin `json:"installedPlugins"`

	// phase
	Phase int64 `json:"phase,omitempty"`
}

// Validate validates this grafana status
func (m *GrafanaStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInstalledPlugins(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GrafanaStatus) validateInstalledPlugins(formats strfmt.Registry) error {

	if swag.IsZero(m.InstalledPlugins) { // not required
		return nil
	}

	for i := 0; i < len(m.InstalledPlugins); i++ {

		if err := m.InstalledPlugins[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("installedPlugins" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GrafanaStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrafanaStatus) UnmarshalBinary(b []byte) error {
	var res GrafanaStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
