// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GrafanaPlugin grafana plugin
// swagger:model GrafanaPlugin
type GrafanaPlugin struct {

	// name
	Name int64 `json:"name,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this grafana plugin
func (m *GrafanaPlugin) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrafanaPlugin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrafanaPlugin) UnmarshalBinary(b []byte) error {
	var res GrafanaPlugin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
