apiVersion: v1
kind: Service
metadata:
  name: {{ .GrafanaAuthProxyServiceName }}
  namespace: {{ .Namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: {{ .GrafanaAuthProxyDeploymentName }}