apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: {{ .GrafanaDeploymentName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
      name: grafana
    spec:
      containers:
        - image: '{{ .GrafanaImage }}:{{ .GrafanaVersion }}'
          args:
            - -config=/etc/grafana/grafana.ini
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana-http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/dashboards
              name: {{ .GrafanaProvidersConfigMapName }}
            - mountPath: /etc/grafana/provisioning/datasources
              name: {{ .GrafanaDatasourcesConfigMapName }}
            - mountPath: /etc/grafana-dashboards
              name: {{ .GrafanaDashboardsConfigMapName }}
            - mountPath: /var/lib/grafana
              name: grafana-data
            - mountPath: /var/log/grafana
              name: grafana-logs
            - mountPath: /etc/grafana/
              name: {{ .GrafanaConfigMapName }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .GrafanaServiceAccountName}}
      serviceAccountName: {{ .GrafanaServiceAccountName }}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: {{ .GrafanaProvidersConfigMapName}}
          name: {{ .GrafanaProvidersConfigMapName }}
        - configMap:
            name: {{ .GrafanaDatasourcesConfigMapName }}
          name: {{ .GrafanaDatasourcesConfigMapName }}
        - configMap:
            name: {{ .GrafanaDashboardsConfigMapName }}
          name: {{ .GrafanaDashboardsConfigMapName }}
        - configMap:
            name: {{ .GrafanaConfigMapName }}
          name: {{ .GrafanaConfigMapName }}
        - emptyDir: {}
          name: grafana-data
        - emptyDir: {}
          name: grafana-logs
