{
 "title": "Grafana Operator",
 "description": "Grafana Operator Dashboard.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "kubeStateMetricsJob", "query": "kube-state-metrics" },
   { "name": "k8sClusterLabelKey", "query": "cluster" },
   {
    "name": "cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "label_values(up{job=\"apiserver\"},$k8sClusterLabelKey)"
    }
   },
   {
    "name": "job",
    "label": "Scrape Job",
    "query": {
     "query": "label_values(grafana_operator_grafana_api_requests{$k8sClusterLabelKey=\"$cluster\"},job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=\"$job\", $k8sClusterLabelKey=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\", $k8sClusterLabelKey=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"$kubeStateMetricsJob\", namespace=\"monitoring-system\", pod=~\"$pod\", resource=\"cpu\", $k8sClusterLabelKey=\"$cluster\"}\r\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"$kubeStateMetricsJob\", namespace=\"monitoring-system\", pod=~\"$pod\", resource=\"cpu\", $k8sClusterLabelKey=\"$cluster\"}\r\n)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"$kubeStateMetricsJob\", namespace=\"monitoring-system\", pod=~\"$pod\", resource=\"memory\", $k8sClusterLabelKey=\"$cluster\"}\r\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"$kubeStateMetricsJob\", namespace=\"monitoring-system\", pod=~\"$pod\", resource=\"memory\", $k8sClusterLabelKey=\"$cluster\"}\r\n)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Custom Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CR Initial Sync Durations",
   "type": "stat",
   "description": "Time in ms to sync Custom Resources after operator restart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_operator_dashboards_initial_sync_duration{$k8sClusterLabelKey=\"$cluster\", pod=~\"$pod\", job=\"$job\"})",
     "legendFormat": "Dashboards"
    },
    {
     "expr": "sum(grafana_operator_datasources_initial_sync_duration{$k8sClusterLabelKey=\"$cluster\", pod=~\"$pod\", job=\"$job\"})",
     "legendFormat": "Datasources"
    },
    {
     "expr": "sum(grafana_operator_folders_initial_sync_duration{$k8sClusterLabelKey=\"$cluster\", pod=~\"$pod\", job=\"$job\"})",
     "legendFormat": "Folders"
    }
   ]
  },
  {
   "title": "CR Reconciles",
   "type": "timeseries",
   "description": "Reconciles per Grafana instance",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(grafana_operator_reconciler_reconciles{$k8sClusterLabelKey=\"$cluster\", pod=~\"$pod\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{job=\"$job\", $k8sClusterLabelKey=\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval])) by (pod, name, le))",
     "legendFormat": "{{name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{job=\"$job\", code=~\"2..\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "2xx - {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{job=\"$job\", code=~\"3..\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "3xx - {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{job=\"$job\", code=~\"4..\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "4xx - {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(rest_client_requests_total{job=\"$job\", code=~\"5..\", pod=~\"$pod\", $k8sClusterLabelKey=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "5xx - {{pod}}"
    }
   ]
  },
  {
   "title": "Grafana API Requests",
   "type": "timeseries",
   "description": "Requests against the Grafana api per instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (method, instance_name) (rate(grafana_operator_grafana_api_requests{$k8sClusterLabelKey=\"$cluster\", pod=~\"$pod\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{method}} - {{instance_name}}"
    }
   ]
  }
 ]
}