/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1"
	"github.com/integr8ly/grafana-operator/pkg/client/versioned/scheme"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	"k8s.io/client-go/rest"
)

type IntegreatlyV1alpha1Interface interface {
	RESTClient() rest.Interface
	GrafanaDashboardsGetter
}

type IntegreatlyV1alpha1Client struct {
	restClient rest.Interface
}

func (c *IntegreatlyV1alpha1Client) GrafanaDashboards(namespace string) GrafanaDashboardInterface {
	return newGrafanaDashboards(c, namespace)
}

// NewForConfig creates a new MonitoringV1Client for the given config.
func NewForConfig(c *rest.Config) (*IntegreatlyV1alpha1Client, error) {
	config := *c
	config.GroupVersion = &v1alpha1.SchemeGroupVersion
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &IntegreatlyV1alpha1Client{client}, nil
}

func NewForConfigOrDie(c *rest.Config) *IntegreatlyV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

func New(c rest.Interface) *IntegreatlyV1alpha1Client {
	return &IntegreatlyV1alpha1Client{c}
}

func (c *IntegreatlyV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}