// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/integr8ly/grafana-operator/v3/pkg/api/models"
)

// CreateGrafanaProxyHandlerFunc turns a function with the right signature into a create grafana proxy handler
type CreateGrafanaProxyHandlerFunc func(CreateGrafanaProxyParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateGrafanaProxyHandlerFunc) Handle(params CreateGrafanaProxyParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateGrafanaProxyHandler interface for that can handle valid create grafana proxy params
type CreateGrafanaProxyHandler interface {
	Handle(CreateGrafanaProxyParams, *models.Principal) middleware.Responder
}

// NewCreateGrafanaProxy creates a new http.Handler for the create grafana proxy operation
func NewCreateGrafanaProxy(ctx *middleware.Context, handler CreateGrafanaProxyHandler) *CreateGrafanaProxy {
	return &CreateGrafanaProxy{Context: ctx, Handler: handler}
}

/*CreateGrafanaProxy swagger:route POST /api/v1/grafanaproxy createGrafanaProxy

Create a Grafana Proxy instance

*/
type CreateGrafanaProxy struct {
	Context *middleware.Context
	Handler CreateGrafanaProxyHandler
}

func (o *CreateGrafanaProxy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateGrafanaProxyParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
