// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/integr8ly/grafana-operator/v3/pkg/api/models"
)

// CreateGrafanaProxyCreatedCode is the HTTP code returned for type CreateGrafanaProxyCreated
const CreateGrafanaProxyCreatedCode int = 201

/*CreateGrafanaProxyCreated OK

swagger:response createGrafanaProxyCreated
*/
type CreateGrafanaProxyCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreateGrafanaProxyCreatedBody `json:"body,omitempty"`
}

// NewCreateGrafanaProxyCreated creates CreateGrafanaProxyCreated with default headers values
func NewCreateGrafanaProxyCreated() *CreateGrafanaProxyCreated {

	return &CreateGrafanaProxyCreated{}
}

// WithPayload adds the payload to the create grafana proxy created response
func (o *CreateGrafanaProxyCreated) WithPayload(payload *models.CreateGrafanaProxyCreatedBody) *CreateGrafanaProxyCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create grafana proxy created response
func (o *CreateGrafanaProxyCreated) SetPayload(payload *models.CreateGrafanaProxyCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGrafanaProxyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateGrafanaProxyDefault Error

swagger:response createGrafanaProxyDefault
*/
type CreateGrafanaProxyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateGrafanaProxyDefault creates CreateGrafanaProxyDefault with default headers values
func NewCreateGrafanaProxyDefault(code int) *CreateGrafanaProxyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateGrafanaProxyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create grafana proxy default response
func (o *CreateGrafanaProxyDefault) WithStatusCode(code int) *CreateGrafanaProxyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create grafana proxy default response
func (o *CreateGrafanaProxyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create grafana proxy default response
func (o *CreateGrafanaProxyDefault) WithPayload(payload *models.Error) *CreateGrafanaProxyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create grafana proxy default response
func (o *CreateGrafanaProxyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGrafanaProxyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
