FROM registry.svc.ci.openshift.org/openshift/release:golang-1.13
LABEL maintainer="pbraun@redhat.com"

ENV OPERATOR_SDK_VERSION=v1.13.1 \
    GOFLAGS=""
# install operator-sdk
RUN curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu && \
    mv operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu /usr/bin/operator-sdk && \
    chmod +x /usr/bin/operator-sdk