name: hugo (reusable)
on:
  workflow_call:
    inputs:
      upload_artifact:
        description: whether to upload artifact
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dart-sass
        uses: ./.github/actions/install-dart-sass

      - name: Restore ~/go/bin
        uses: ./.github/actions/bingo-restore

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install Node.js dependencies
        run: |
          cd hugo
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - name: Build with Hugo
        run: |
          make hugo

      - name: Setup Pages
        if: ${{ inputs.upload_artifact }}
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./hugo/public
