name: hugo (reusable)
on:
  workflow_call:
    inputs:
      upload_artifact:
        description: whether to upload artifact
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DART_SASS_VERSION: 1.86.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: |
          cd hugo
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - name: Install Dart Sass
        run: |
          wget -O ${{ runner.temp }}/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64-musl.tar.gz \
          && tar -xvf ${{ runner.temp }}/dart-sass.tar.gz -C ${{ runner.temp }}/ \
          && echo "${{ runner.temp }}/dart-sass" >> $GITHUB_PATH

      - name: Build with Hugo
        run: |
          make hugo

      - name: Setup Pages
        if: ${{ inputs.upload_artifact }}
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./hugo/public
